<?php

namespace App\Support;

use Illuminate\Support\Facades\Storage;

/**
 * Resolves storefront image URLs, preferring a pre-generated WebP derivative
 * when one exists.
 *
 * Product photos are shot at 853x1280 (~150 KB each). Listing pages show them
 * in a ~235 px tall box, so serving the original there wastes most of the
 * bytes. `php artisan images:optimize` writes smaller WebP copies next to the
 * originals and this class picks them up; if a derivative is missing for any
 * reason the original is served, so the site never breaks on a missing file.
 */
class Media
{
    /** Widths generated by the optimize command. */
    public const WIDTHS = [500, 800];

    /** Derivative folder, relative to the image's own directory. */
    public const THUMB_DIR = 'thumbs';

    /** @var array<string, bool> Per-request cache of disk lookups. */
    private static array $exists = [];

    /**
     * Public URL for a stored image path such as `products/gallery/x.jpeg`.
     *
     * @param  int|null  $width  One of self::WIDTHS, or null for the original.
     */
    public static function url(?string $path, ?int $width = null): ?string
    {
        if (blank($path)) {
            return null;
        }

        if ($width !== null) {
            $derivative = static::derivativePath($path, $width);

            if ($derivative !== null) {
                if (static::exists($derivative)) {
                    return asset('storage/' . $derivative);
                }

                // Missing derivative - build it now, so images uploaded from
                // the dashboard start being served resized straight away
                // instead of waiting for someone to run images:optimize.
                if (ImageDerivatives::ensure($path, $width)) {
                    static::$exists[$derivative] = true;

                    return asset('storage/' . $derivative);
                }
            }
        }

        return asset('storage/' . $path);
    }

    /** Where the WebP copy of $path at $width lives, or null if not derivable. */
    public static function derivativePath(string $path, int $width): ?string
    {
        $extension = pathinfo($path, PATHINFO_EXTENSION);

        if (! in_array(strtolower($extension), ['jpg', 'jpeg', 'png', 'webp'], true)) {
            return null;
        }

        $directory = trim(pathinfo($path, PATHINFO_DIRNAME), '.' . DIRECTORY_SEPARATOR . '/');
        $name = pathinfo($path, PATHINFO_FILENAME);

        $prefix = $directory === '' ? '' : $directory . '/';

        return $prefix . static::THUMB_DIR . '/' . $name . '-' . $width . '.webp';
    }

    private static function exists(string $path): bool
    {
        return static::$exists[$path] ??= Storage::disk('public')->exists($path);
    }

    /** Only used by tests and the optimize command. */
    public static function forgetExistsCache(): void
    {
        static::$exists = [];
    }
}
